import pymysql.cursors
import random
import string


def make_dataset(num, pre_dataset):
    dataset = []
    temp = []
    num_10 = [10, 100, 1000, 10000]
    len_preset = len(pre_dataset)

    for i in range(len_preset):
        frequency = random.randrange(1, 20)
        amount = random.random() * random.choice(num_10)
        dataset.append((frequency, amount, pre_dataset[i].rstrip()))

    for i in range(num - len_preset):
        frequency = random.randrange(1, 20)
        amount = random.random() * random.choice(num_10)
        value = "".join([random.choice(string.ascii_letters) for _ in range(30)])
        while value in dataset:
            value = "".join([random.choice(string.ascii_letters) for _ in range(30)])
        dataset.append((frequency, amount, value))

    return dataset

def INSERT_DB(dataset, conn, table):
    curs = conn.cursor()

    query = "INSERT INTO "+table+"(frequency, amount, value) VALUES(%s, %s, %s)"
    print(query, dataset)
    for i in range(len(dataset)):
        curs.execute(query, dataset[i])

    conn.commit()

def SELECT_DB(conn,table):
    curs = conn.cursor()

    query = "SELECT * FROM " + table
    curs.execute(query)

    rows = curs.fetchall()

    return rows



# Preset value, these values may be match between client and server inspect
preset_values = [
        "preset customer  1", 
        "preset customer  2", 
        "preset customer  3", 
        "preset customer  4", 
        "preset customer  5", 
        "preset customer  6", 
        "preset customer  7", 
        "preset customer  8", 
        "preset customer  9", 
        "preset customer  10", 
        "preset customer  11", 
        "preset customer  12", 
        "preset customer  13", 
        "preset customer  14", 
        "preset customer  15", 
        "preset customer  16", 
        "preset customer  17", 
        "preset customer  18", 
        "preset customer  19", 
        "preset customer  20", 
        "preset customer  21", 
        "preset customer  22", 
        "preset customer  23", 
        "preset customer  24", 
        "preset customer  25", 
        "preset customer  26", 
        "preset customer  27", 
        "preset customer  28", 
        "preset customer  29", 
        "preset customer  30", 
        "preset customer  31", 
        "preset customer  32", 
        "preset customer  33", 
        "preset customer  34", 
        "preset customer  35", 
        "preset customer  36", 
        "preset customer  37", 
        "preset customer  38", 
        "preset customer  39", 
        "preset customer  40", 
        "preset customer  41", 
        "preset customer  42", 
        "preset customer  43", 
        "preset customer  44", 
        "preset customer  45", 
        "preset customer  46", 
        "preset customer  47", 
        "preset customer  48", 
        "preset customer  49", 
        "preset customer  50", 
"preset customer  51", 
    "preset customer  52", 
    "preset customer  53", 
    "preset customer  54", 
    "preset customer  55", 
    "preset customer  56", 
    "preset customer  57", 
    "preset customer  58", 
    "preset customer  59", 
    "preset customer  60", 
    "preset customer  61", 
    "preset customer  62", 
    "preset customer  63", 
    "preset customer  64", 
    "preset customer  65", 
    "preset customer  66", 
    "preset customer  67", 
    "preset customer  68", 
    "preset customer  69", 
    "preset customer  70", 
    "preset customer  71", 
    "preset customer  72", 
    "preset customer  73", 
    "preset customer  74", 
    "preset customer  75", 
    "preset customer  76", 
    "preset customer  77", 
    "preset customer  78", 
    "preset customer  79", 
    "preset customer  80", 
    "preset customer  81", 
    "preset customer  82", 
    "preset customer  83", 
    "preset customer  84", 
    "preset customer  85", 
    "preset customer  86", 
    "preset customer  87", 
    "preset customer  88", 
    "preset customer  89", 
    "preset customer  90", 
    "preset customer  91", 
    "preset customer  92", 
    "preset customer  93", 
    "preset customer  94", 
    "preset customer  95", 
    "preset customer  96", 
    "preset customer  97", 
    "preset customer  98", 
    "preset customer  99", 
    "preset customer  100" ,
    "preset customer  101" ,
    "preset customer  102" ,
    "preset customer  103" ,
    "preset customer  104" ,
    "preset customer  105" ,
    "preset customer  106" ,
    "preset customer  107" ,
    "preset customer  108" ,
    "preset customer  109" ,
    "preset customer  110" ,
    "preset customer  111" ,
    "preset customer  112" ,
    "preset customer  113" ,
    "preset customer  114" ,
    "preset customer  115" ,
    "preset customer  116" ,
    "preset customer  117" ,
    "preset customer  118" ,
    "preset customer  119" ,
    "preset customer  120" ,
    "preset customer  121" ,
    "preset customer  122" ,
    "preset customer  123" ,
    "preset customer  124" ,
    "preset customer  125" ,
    "preset customer  126" ,
    "preset customer  127" ,
    "preset customer  128" ,
    "preset customer  129" ,
    "preset customer  130" ,
    "preset customer  131" ,
    "preset customer  132" ,
    "preset customer  133" ,
    "preset customer  134" ,
    "preset customer  135" ,
    "preset customer  136" ,
    "preset customer  137" ,
    "preset customer  138" ,
    "preset customer  139" ,
    "preset customer  140" ,
    "preset customer  141" ,
    "preset customer  142" ,
    "preset customer  143" ,
    "preset customer  144" ,
    "preset customer  145" ,
    "preset customer  146" ,
    "preset customer  147" ,
    "preset customer  148" ,
    "preset customer  149" ,
    "preset customer  150" ,
    "preset customer  151" ,
    "preset customer  152" ,
    "preset customer  153" ,
    "preset customer  154" ,
    "preset customer  155" ,
    "preset customer  156" ,
    "preset customer  157" ,
    "preset customer  158" ,
    "preset customer  159" ,
    "preset customer  160" ,
    "preset customer  161" ,
    "preset customer  162" ,
    "preset customer  163" ,
    "preset customer  164" ,
    "preset customer  165" ,
    "preset customer  166" ,
    "preset customer  167" ,
    "preset customer  168" ,
    "preset customer  169" ,
    "preset customer  170" ,
    "preset customer  171" ,
    "preset customer  172" ,
    "preset customer  173" ,
    "preset customer  174" ,
    "preset customer  175" ,
    "preset customer  176" ,
    "preset customer  177" ,
    "preset customer  178" ,
    "preset customer  179" ,
    "preset customer  180" ,
    "preset customer  181" ,
    "preset customer  182" ,
    "preset customer  183" ,
    "preset customer  184" ,
    "preset customer  185" ,
    "preset customer  186" ,
    "preset customer  187" ,
    "preset customer  188" ,
    "preset customer  189" ,
    "preset customer  190" ,
    "preset customer  191" ,
    "preset customer  192" ,
    "preset customer  193" ,
    "preset customer  194" ,
    "preset customer  195" ,
    "preset customer  196" ,
    "preset customer  197" ,
    "preset customer  198" ,
    "preset customer  199" ,
    "preset customer  200" ,
    "preset customer  201" ,
    "preset customer  202" ,
    "preset customer  203" ,
    "preset customer  204" ,
    "preset customer  205" ,
    "preset customer  206" ,
    "preset customer  207" ,
    "preset customer  208" ,
    "preset customer  209" ,
    "preset customer  210" ,
    "preset customer  211" ,
    "preset customer  212" ,
    "preset customer  213" ,
    "preset customer  214" ,
    "preset customer  215" ,
    "preset customer  216" ,
    "preset customer  217" ,
    "preset customer  218" ,
    "preset customer  219" ,
    "preset customer  220" ,
    "preset customer  221" ,
    "preset customer  222" ,
    "preset customer  223" ,
    "preset customer  224" ,
    "preset customer  225" ,
    "preset customer  226" ,
    "preset customer  227" ,
    "preset customer  228" ,
    "preset customer  229" ,
    "preset customer  230" ,
    "preset customer  231" ,
    "preset customer  232" ,
    "preset customer  233" ,
    "preset customer  234" ,
    "preset customer  235" ,
    "preset customer  236" ,
    "preset customer  237" ,
    "preset customer  238" ,
    "preset customer  239" ,
    "preset customer  240" ,
    "preset customer  241" ,
    "preset customer  242" ,
    "preset customer  243" ,
    "preset customer  244" ,
    "preset customer  245" ,
    "preset customer  246" ,
    "preset customer  247" ,
    "preset customer  248" ,
    "preset customer  249" ,
    "preset customer  250" ,
    "preset customer  251" ,
    "preset customer  252" ,
    "preset customer  253" ,
    "preset customer  254" ,
    "preset customer  255" ,
    "preset customer  256" ,
    "preset customer  257" ,
    "preset customer  258" ,
    "preset customer  259" ,
    "preset customer  260" ,
    "preset customer  261" ,
    "preset customer  262" ,
    "preset customer  263" ,
    "preset customer  264" ,
    "preset customer  265" ,
    "preset customer  266" ,
    "preset customer  267" ,
    "preset customer  268" ,
    "preset customer  269" ,
    "preset customer  270" ,
    "preset customer  271" ,
    "preset customer  272" ,
    "preset customer  273" ,
    "preset customer  274" ,
    "preset customer  275" ,
    "preset customer  276" ,
    "preset customer  277" ,
    "preset customer  278" ,
    "preset customer  279" ,
    "preset customer  280" ,
    "preset customer  281" ,
    "preset customer  282" ,
    "preset customer  283" ,
    "preset customer  284" ,
    "preset customer  285" ,
    "preset customer  286" ,
    "preset customer  287" ,
    "preset customer  288" ,
    "preset customer  289" ,
    "preset customer  290" ,
    "preset customer  291" ,
    "preset customer  292" ,
    "preset customer  293" ,
    "preset customer  294" ,
    "preset customer  295" ,
    "preset customer  296" ,
    "preset customer  297" ,
    "preset customer  298" ,
    "preset customer  299" ,
    "preset customer  300" ,
    "preset customer  301" ,
    "preset customer  302" ,
    "preset customer  303" ,
    "preset customer  304" ,
    "preset customer  305" ,
    "preset customer  306" ,
    "preset customer  307" ,
    "preset customer  308" ,
    "preset customer  309" ,
    "preset customer  310" ,
    "preset customer  311" ,
    "preset customer  312" ,
    "preset customer  313" ,
    "preset customer  314" ,
    "preset customer  315" ,
    "preset customer  316" ,
    "preset customer  317" ,
    "preset customer  318" ,
    "preset customer  319" ,
    "preset customer  320" ,
    "preset customer  321" ,
    "preset customer  322" ,
    "preset customer  323" ,
    "preset customer  324" ,
    "preset customer  325" ,
    "preset customer  326" ,
    "preset customer  327" ,
    "preset customer  328" ,
    "preset customer  329" ,
    "preset customer  330" ,
    "preset customer  331" ,
    "preset customer  332" ,
    "preset customer  333" ,
    "preset customer  334" ,
    "preset customer  335" ,
    "preset customer  336" ,
    "preset customer  337" ,
    "preset customer  338" ,
    "preset customer  339" ,
    "preset customer  340" ,
    "preset customer  341" ,
    "preset customer  342" ,
    "preset customer  343" ,
    "preset customer  344" ,
    "preset customer  345" ,
    "preset customer  346" ,
    "preset customer  347" ,
    "preset customer  348" ,
    "preset customer  349" ,
    "preset customer  350" ,
    "preset customer  351" ,
    "preset customer  352" ,
    "preset customer  353" ,
    "preset customer  354" ,
    "preset customer  355" ,
    "preset customer  356" ,
    "preset customer  357" ,
    "preset customer  358" ,
    "preset customer  359" ,
    "preset customer  360" ,
    "preset customer  361" ,
    "preset customer  362" ,
    "preset customer  363" ,
    "preset customer  364" ,
    "preset customer  365" ,
    "preset customer  366" ,
    "preset customer  367" ,
    "preset customer  368" ,
    "preset customer  369" ,
    "preset customer  370" ,
    "preset customer  371" ,
    "preset customer  372" ,
    "preset customer  373" ,
    "preset customer  374" ,
    "preset customer  375" ,
    "preset customer  376" ,
    "preset customer  377" ,
    "preset customer  378" ,
    "preset customer  379" ,
    "preset customer  380" ,
    "preset customer  381" ,
    "preset customer  382" ,
    "preset customer  383" ,
    "preset customer  384" ,
    "preset customer  385" ,
    "preset customer  386" ,
    "preset customer  387" ,
    "preset customer  388" ,
    "preset customer  389" ,
    "preset customer  390" ,
    "preset customer  391" ,
    "preset customer  392" ,
    "preset customer  393" ,
    "preset customer  394" ,
    "preset customer  395" ,
    "preset customer  396" ,
    "preset customer  397" ,
    "preset customer  398" ,
    "preset customer  399" ,
    "preset customer  400" ,
    "preset customer  401" ,
    "preset customer  402" ,
    "preset customer  403" ,
    "preset customer  404" ,
    "preset customer  405" ,
    "preset customer  406" ,
    "preset customer  407" ,
    "preset customer  408" ,
    "preset customer  409" ,
    "preset customer  410" ,
    "preset customer  411" ,
    "preset customer  412" ,
    "preset customer  413" ,
    "preset customer  414" ,
    "preset customer  415" ,
    "preset customer  416" ,
    "preset customer  417" ,
    "preset customer  418" ,
    "preset customer  419" ,
    "preset customer  420" ,
    "preset customer  421" ,
    "preset customer  422" ,
    "preset customer  423" ,
    "preset customer  424" ,
    "preset customer  425" ,
    "preset customer  426" ,
    "preset customer  427" ,
    "preset customer  428" ,
    "preset customer  429" ,
    "preset customer  430" ,
    "preset customer  431" ,
    "preset customer  432" ,
    "preset customer  433" ,
    "preset customer  434" ,
    "preset customer  435" ,
    "preset customer  436" ,
    "preset customer  437" ,
    "preset customer  438" ,
    "preset customer  439" ,
    "preset customer  440" ,
    "preset customer  441" ,
    "preset customer  442" ,
    "preset customer  443" ,
    "preset customer  444" ,
    "preset customer  445" ,
    "preset customer  446" ,
    "preset customer  447" ,
    "preset customer  448" ,
    "preset customer  449" ,
    "preset customer  450" ,
    "preset customer  451" ,
    "preset customer  452" ,
    "preset customer  453" ,
    "preset customer  454" ,
    "preset customer  455" ,
    "preset customer  456" ,
    "preset customer  457" ,
    "preset customer  458" ,
    "preset customer  459" ,
    "preset customer  460" ,
    "preset customer  461" ,
    "preset customer  462" ,
    "preset customer  463" ,
    "preset customer  464" ,
    "preset customer  465" ,
    "preset customer  466" ,
    "preset customer  467" ,
    "preset customer  468" ,
    "preset customer  469" ,
    "preset customer  470" ,
    "preset customer  471" ,
    "preset customer  472" ,
    "preset customer  473" ,
    "preset customer  474" ,
    "preset customer  475" ,
    "preset customer  476" ,
    "preset customer  477" ,
    "preset customer  478" ,
    "preset customer  479" ,
    "preset customer  480" ,
    "preset customer  481" ,
    "preset customer  482" ,
    "preset customer  483" ,
    "preset customer  484" ,
    "preset customer  485" ,
    "preset customer  486" ,
    "preset customer  487" ,
    "preset customer  488" ,
    "preset customer  489" ,
    "preset customer  490" ,
    "preset customer  491" ,
    "preset customer  492" ,
    "preset customer  493" ,
    "preset customer  494" ,
    "preset customer  495" ,
    "preset customer  496" ,
    "preset customer  497" ,
    "preset customer  498" ,
    "preset customer  499" ,
    "preset customer  500" ,
    "infected passenger 1" ,
    "infected passenger 2" ,
    "infected passenger 3" ,
    "infected passenger 4" ,
    "infected passenger 5" ,
    "infected passenger 6" ,
    "infected passenger 7" ,
    "infected passenger 8" ,
    "infected passenger 9" ,
    "infected passenger 10 ",
    "infected passenger 11 ",
    "infected passenger 12 ",
    "infected passenger 13 ",
    "infected passenger 14 ",
    "infected passenger 15 ",
    "infected passenger 16 ",
    "infected passenger 17 ",
    "infected passenger 18 ",
    "infected passenger 19 ",
    "infected passenger 20 ",
    "infected passenger 21 ",
    "infected passenger 22 ",
    "infected passenger 23 ",
    "infected passenger 24 ",
    "infected passenger 25 ",
    "infected passenger 26 ",
    "infected passenger 27 ",
    "infected passenger 28 ",
    "infected passenger 29 ",
    "infected passenger 30 ",
    "infected passenger 31 ",
    "infected passenger 32 ",
    "infected passenger 33 ",
    "infected passenger 34 ",
    "infected passenger 35 ",
    "infected passenger 36 ",
    "infected passenger 37 ",
    "infected passenger 38 ",
    "infected passenger 39 ",
    "infected passenger 40 ",
    "infected passenger 41 ",
    "infected passenger 42 ",
    "infected passenger 43 ",
    "infected passenger 44 ",
    "infected passenger 45 ",
    "infected passenger 46 ",
    "infected passenger 47 ",
    "infected passenger 48 ",
    "infected passenger 49 ",
    "infected passenger 50 ",
    "infected passenger 51 ",
    "infected passenger 52 ",
    "infected passenger 53 ",
    "infected passenger 54 ",
    "infected passenger 55 ",
    "infected passenger 56 ",
    "infected passenger 57 ",
    "infected passenger 58 ",
    "infected passenger 59 ",
    "infected passenger 60 ",
    "infected passenger 61 ",
    "infected passenger 62 ",
    "infected passenger 63 ",
    "infected passenger 64 ",
    "infected passenger 65 ",
    "infected passenger 66 ",
    "infected passenger 67 ",
    "infected passenger 68 ",
    "infected passenger 69 ",
    "infected passenger 70 ",
    "infected passenger 71 ",
    "infected passenger 72 ",
    "infected passenger 73 ",
    "infected passenger 74 ",
    "infected passenger 75 ",
    "infected passenger 76 ",
    "infected passenger 77 ",
    "infected passenger 78 ",
    "infected passenger 79 ",
    "infected passenger 80 ",
    "infected passenger 81 ",
    "infected passenger 82 ",
    "infected passenger 83 ",
    "infected passenger 84 ",
    "infected passenger 85 ",
    "infected passenger 86 ",
    "infected passenger 87 ",
    "infected passenger 88 ",
    "infected passenger 89 ",
    "infected passenger 90 ",
    "infected passenger 91 ",
    "infected passenger 92 ",
    "infected passenger 93 ",
    "infected passenger 94 ",
    "infected passenger 95 ",
    "infected passenger 96 ",
    "infected passenger 97 ",
    "infected passenger 98 ",
    "infected passenger 99 ",
    "infected passenger 100	", 
    "infected passenger 101	", 
    "infected passenger 102	", 
    "infected passenger 103	", 
    "infected passenger 104	", 
    "infected passenger 105	", 
    "infected passenger 106	", 
    "infected passenger 107	", 
    "infected passenger 108	", 
    "infected passenger 109	", 
    "infected passenger 110	", 
    "infected passenger 111	", 
    "infected passenger 112	", 
    "infected passenger 113	", 
    "infected passenger 114	", 
    "infected passenger 115	", 
    "infected passenger 116	", 
    "infected passenger 117	", 
    "infected passenger 118	", 
    "infected passenger 119	", 
    "infected passenger 120	", 
    "infected passenger 121	", 
    "infected passenger 122	", 
    "infected passenger 123	", 
    "infected passenger 124	", 
    "infected passenger 125	", 
    "infected passenger 126	", 
    "infected passenger 127	", 
    "infected passenger 128	", 
    "infected passenger 129	", 
    "infected passenger 130	", 
    "infected passenger 131	", 
    "infected passenger 132	", 
    "infected passenger 133	", 
    "infected passenger 134	", 
    "infected passenger 135	", 
    "infected passenger 136	", 
    "infected passenger 137	", 
    "infected passenger 138	", 
    "infected passenger 139	", 
    "infected passenger 140	", 
    "infected passenger 141	", 
    "infected passenger 142	", 
    "infected passenger 143	", 
    "infected passenger 144	", 
    "infected passenger 145	", 
    "infected passenger 146	", 
    "infected passenger 147	", 
    "infected passenger 148	", 
    "infected passenger 149	", 
    "infected passenger 150	", 
    "infected passenger 151	", 
    "infected passenger 152	", 
    "infected passenger 153	", 
    "infected passenger 154	", 
    "infected passenger 155	", 
    "infected passenger 156	", 
    "infected passenger 157	", 
    "infected passenger 158	", 
    "infected passenger 159	", 
    "infected passenger 160	", 
    "infected passenger 161	", 
    "infected passenger 162	", 
    "infected passenger 163	", 
    "infected passenger 164	", 
    "infected passenger 165	", 
    "infected passenger 166	", 
    "infected passenger 167	", 
    "infected passenger 168	", 
    "infected passenger 169	", 
    "infected passenger 170	", 
    "infected passenger 171	", 
    "infected passenger 172	", 
    "infected passenger 173	", 
    "infected passenger 174	", 
    "infected passenger 175	", 
    "infected passenger 176	", 
    "infected passenger 177	", 
    "infected passenger 178	", 
    "infected passenger 179	", 
    "infected passenger 180	", 
    "infected passenger 181	", 
    "infected passenger 182	", 
    "infected passenger 183	", 
    "infected passenger 184	", 
    "infected passenger 185	", 
    "infected passenger 186	", 
    "infected passenger 187	", 
    "infected passenger 188	", 
    "infected passenger 189	", 
    "infected passenger 190	", 
    "infected passenger 191	", 
    "infected passenger 192	", 
    "infected passenger 193	", 
    "infected passenger 194	", 
    "infected passenger 195	", 
    "infected passenger 196	", 
    "infected passenger 197	", 
    "infected passenger 198	", 
    "infected passenger 199	", 
    "infected passenger 200	", 
    "infected passenger 201	", 
    "infected passenger 202	", 
    "infected passenger 203	", 
    "infected passenger 204	", 
    "infected passenger 205	", 
    "infected passenger 206	", 
    "infected passenger 207	", 
    "infected passenger 208	", 
    "infected passenger 209	", 
    "infected passenger 210	", 
    "infected passenger 211	", 
    "infected passenger 212	", 
    "infected passenger 213	", 
    "infected passenger 214	", 
    "infected passenger 215	", 
    "infected passenger 216	", 
    "infected passenger 217	", 
    "infected passenger 218	", 
    "infected passenger 219	", 
    "infected passenger 220	", 
    "infected passenger 221	", 
    "infected passenger 222	", 
    "infected passenger 223	", 
    "infected passenger 224	", 
    "infected passenger 225	", 
    "infected passenger 226	", 
    "infected passenger 227	", 
    "infected passenger 228	", 
    "infected passenger 229	", 
    "infected passenger 230	", 
    "infected passenger 231	", 
    "infected passenger 232	", 
    "infected passenger 233	", 
    "infected passenger 234	", 
    "infected passenger 235	", 
    "infected passenger 236	", 
    "infected passenger 237	", 
    "infected passenger 238	", 
    "infected passenger 239	", 
    "infected passenger 240	", 
    "infected passenger 241	", 
    "infected passenger 242	", 
    "infected passenger 243	", 
    "infected passenger 244	", 
    "infected passenger 245	", 
    "infected passenger 246	", 
    "infected passenger 247	", 
    "infected passenger 248	", 
    "infected passenger 249	", 
    "infected passenger 250	", 
    "infected passenger 251	", 
    "infected passenger 252	", 
    "infected passenger 253	", 
    "infected passenger 254	", 
    "infected passenger 255	", 
    "infected passenger 256	", 
    "infected passenger 257	", 
    "infected passenger 258	", 
    "infected passenger 259	", 
    "infected passenger 260	", 
    "infected passenger 261	", 
    "infected passenger 262	", 
    "infected passenger 263	", 
    "infected passenger 264	", 
    "infected passenger 265	", 
    "infected passenger 266	", 
    "infected passenger 267	", 
    "infected passenger 268	", 
    "infected passenger 269	", 
    "infected passenger 270	", 
    "infected passenger 271	", 
    "infected passenger 272	", 
    "infected passenger 273	", 
    "infected passenger 274	", 
    "infected passenger 275	", 
    "infected passenger 276	", 
    "infected passenger 277	", 
    "infected passenger 278	", 
    "infected passenger 279	", 
    "infected passenger 280	", 
    "infected passenger 281	", 
    "infected passenger 282	", 
    "infected passenger 283	", 
    "infected passenger 284	", 
    "infected passenger 285	", 
    "infected passenger 286	", 
    "infected passenger 287	", 
    "infected passenger 288	", 
    "infected passenger 289	", 
    "infected passenger 290	", 
    "infected passenger 291	", 
    "infected passenger 292	", 
    "infected passenger 293	", 
    "infected passenger 294	", 
    "infected passenger 295	", 
    "infected passenger 296	", 
    "infected passenger 297	", 
    "infected passenger 298	", 
    "infected passenger 299	", 
    "infected passenger 300	", 
    "infected passenger 301	", 
    "infected passenger 302	", 
    "infected passenger 303	", 
    "infected passenger 304	", 
    "infected passenger 305	", 
    "infected passenger 306	", 
    "infected passenger 307	", 
    "infected passenger 308	", 
    "infected passenger 309	", 
    "infected passenger 310	", 
    "infected passenger 311	", 
    "infected passenger 312	", 
    "infected passenger 313	", 
    "infected passenger 314	", 
    "infected passenger 315	", 
    "infected passenger 316	", 
    "infected passenger 317	", 
    "infected passenger 318	", 
    "infected passenger 319	", 
    "infected passenger 320	", 
    "infected passenger 321	", 
    "infected passenger 322	", 
    "infected passenger 323	", 
    "infected passenger 324	", 
    "infected passenger 325	", 
    "infected passenger 326	", 
    "infected passenger 327	", 
    "infected passenger 328	", 
    "infected passenger 329	", 
    "infected passenger 330	", 
    "infected passenger 331	", 
    "infected passenger 332	", 
    "infected passenger 333	", 
    "infected passenger 334	", 
    "infected passenger 335	", 
    "infected passenger 336	", 
    "infected passenger 337	", 
    "infected passenger 338	", 
    "infected passenger 339	", 
    "infected passenger 340	", 
    "infected passenger 341	", 
    "infected passenger 342	", 
    "infected passenger 343	", 
    "infected passenger 344	", 
    "infected passenger 345	", 
    "infected passenger 346	", 
    "infected passenger 347	", 
    "infected passenger 348	", 
    "infected passenger 349	", 
    "infected passenger 350	", 
    "infected passenger 351	", 
    "infected passenger 352	", 
    "infected passenger 353	", 
    "infected passenger 354	", 
    "infected passenger 355	", 
    "infected passenger 356	", 
    "infected passenger 357	", 
    "infected passenger 358	", 
    "infected passenger 359	", 
    "infected passenger 360	", 
    "infected passenger 361	", 
    "infected passenger 362	", 
    "infected passenger 363	", 
    "infected passenger 364	", 
    "infected passenger 365	", 
    "infected passenger 366	", 
    "infected passenger 367	", 
    "infected passenger 368	", 
    "infected passenger 369	", 
    "infected passenger 370	", 
    "infected passenger 371	", 
    "infected passenger 372	", 
    "infected passenger 373	", 
    "infected passenger 374	", 
    "infected passenger 375	", 
    "infected passenger 376	", 
    "infected passenger 377	", 
    "infected passenger 378	", 
    "infected passenger 379	", 
    "infected passenger 380	", 
    "infected passenger 381	", 
    "infected passenger 382	", 
    "infected passenger 383	", 
    "infected passenger 384	", 
    "infected passenger 385	", 
    "infected passenger 386	", 
    "infected passenger 387	", 
    "infected passenger 388	", 
    "infected passenger 389	", 
    "infected passenger 390	", 
    "infected passenger 391	", 
    "infected passenger 392	", 
    "infected passenger 393	", 
    "infected passenger 394	", 
    "infected passenger 395	", 
    "infected passenger 396	", 
    "infected passenger 397	", 
    "infected passenger 398	", 
    "infected passenger 399	", 
    "infected passenger 400	", 
    "infected passenger 401	", 
    "infected passenger 402	", 
    "infected passenger 403	", 
    "infected passenger 404	", 
    "infected passenger 405	", 
    "infected passenger 406	", 
    "infected passenger 407	", 
    "infected passenger 408	", 
    "infected passenger 409	", 
    "infected passenger 410	", 
    "infected passenger 411	", 
    "infected passenger 412	", 
    "infected passenger 413	", 
    "infected passenger 414	", 
    "infected passenger 415	", 
    "infected passenger 416	", 
    "infected passenger 417	", 
    "infected passenger 418	", 
    "infected passenger 419	", 
    "infected passenger 420	", 
    "infected passenger 421	", 
    "infected passenger 422	", 
    "infected passenger 423	", 
    "infected passenger 424	", 
    "infected passenger 425	", 
    "infected passenger 426	", 
    "infected passenger 427	", 
    "infected passenger 428	", 
    "infected passenger 429	", 
    "infected passenger 430	", 
    "infected passenger 431	", 
    "infected passenger 432	", 
    "infected passenger 433	", 
    "infected passenger 434	", 
    "infected passenger 435	", 
    "infected passenger 436	", 
    "infected passenger 437	", 
    "infected passenger 438	", 
    "infected passenger 439	", 
    "infected passenger 440	", 
    "infected passenger 441	", 
    "infected passenger 442	", 
    "infected passenger 443	", 
    "infected passenger 444	", 
    "infected passenger 445	", 
    "infected passenger 446	", 
    "infected passenger 447	", 
    "infected passenger 448	", 
    "infected passenger 449	", 
    "infected passenger 450	", 
    "infected passenger 451	", 
    "infected passenger 452	", 
    "infected passenger 453	", 
    "infected passenger 454	", 
    "infected passenger 455	", 
    "infected passenger 456	", 
    "infected passenger 457	", 
    "infected passenger 458	", 
    "infected passenger 459	", 
    "infected passenger 460	", 
    "infected passenger 461	", 
    "infected passenger 462	", 
    "infected passenger 463	", 
    "infected passenger 464	", 
    "infected passenger 465	", 
    "infected passenger 466	", 
    "infected passenger 467	", 
    "infected passenger 468	", 
    "infected passenger 469	", 
    "infected passenger 470	", 
    "infected passenger 471	", 
    "infected passenger 472	", 
    "infected passenger 473	", 
    "infected passenger 474	", 
    "infected passenger 475	", 
    "infected passenger 476	", 
    "infected passenger 477	", 
    "infected passenger 478	", 
    "infected passenger 479	", 
    "infected passenger 480	", 
    "infected passenger 481	", 
    "infected passenger 482	", 
    "infected passenger 483	", 
    "infected passenger 484	", 
    "infected passenger 485	", 
    "infected passenger 486	", 
    "infected passenger 487	", 
    "infected passenger 488	", 
    "infected passenger 489	", 
    "infected passenger 490	", 
    "infected passenger 491	", 
    "infected passenger 492	", 
    "infected passenger 493	", 
    "infected passenger 494	", 
    "infected passenger 495	", 
    "infected passenger 496	", 
    "infected passenger 497	", 
    "infected passenger 498	", 
    "infected passenger 499	", 
    "infected passenger 500	", 
        ]
